Update action.yml

diff --git a/post-test-results-to-azure-devops/action.yml b/post-test-results-to-azure-devops/action.yml
--- a/post-test-results-to-azure-devops/action.yml
+++ b/post-test-results-to-azure-devops/action.yml
@@ -32,7 +32,17 @@ runs:
         else
           echo "Python3 is already installed"
         fi
-    
+
+    - name: Debug: List repo root
+      shell: bash
+      run: |
+        echo "Debug: List root folder"
+        ls -la
+        echo "Debug: List nested folder"
+        ls -la ./book-api-rest-assured-test-automation
+        echo "Debug: List actions folder"
+        ls -la ./book-api-rest-assured-test-automation/actions/post-test-results-to-azure-devops || echo "Not found"
+
     - name: Install dependencies
       shell: bash
       run: |
