Update to use python install instead of set up python

diff --git a/post-test-results-to-azure-devops/action.yml b/post-test-results-to-azure-devops/action.yml
--- a/post-test-results-to-azure-devops/action.yml
+++ b/post-test-results-to-azure-devops/action.yml
@@ -22,9 +22,16 @@ runs:
   using: "composite"
 
   steps:
-    - uses: actions/setup-python@v5
-      with:
-        python-version: '3.12'
+    - name: Install Python
+      shell: bash
+      run: |
+        if ! command -v python3 &> /dev/null; then
+          echo "Python3 not found, installing..."
+          apt-get update
+          apt-get install -y python3 python3-pip
+        else
+          echo "Python3 is already installed"
+        fi
     
     - name: Install dependencies
       run: pip install -r ${{ github.action_path }}/requirements.txt
