Update action.yml

diff --git a/allure-report-with-history/action.yml b/allure-report-with-history/action.yml
--- a/allure-report-with-history/action.yml
+++ b/allure-report-with-history/action.yml
@@ -31,6 +31,16 @@ runs:
         shell: bash
         continue-on-error: true
         run: |
+          echo "Checking contents of history folder Before:"
+          ls -l test-results/allure-results/history || echo "No history folder found"
+
+          echo -e "\nContents of history.json (if present) Before:"
+          if [ -f test-results/allure-results/history/history.json ]; then
+            cat test-results/allure-results/history/history.json
+          else
+            echo "history.json not found"
+          fi
+          
           mkdir -p test-results/allure-results/history
           for file in history.json categories-trend.json duration-trend.json retry-trend.json; do
             curl -sfL "https://${GITHUB_REPOSITORY_OWNER}.github.io/${GITHUB_REPOSITORY##*/}/allure-report/history/$file" \
