Update Allure report action to use github pages instead of previous run

diff --git a/allure-report-with-history/action.yml b/allure-report-with-history/action.yml
--- a/allure-report-with-history/action.yml
+++ b/allure-report-with-history/action.yml
@@ -26,46 +26,19 @@ runs:
           mv allure-2.27.0 /opt/allure
           ln -s /opt/allure/bin/allure /usr/bin/allure
 
-      - name: Get Previous Test Execution Workflow Run ID
+      - name: Download Allure History
         if: success() || failure()
-        id: get-run-id
-        uses: actions/github-script@v7
-        with:
-          script: |
-            const workflow_id = "test-execution.yml";
-            const runs = await github.rest.actions.listWorkflowRuns({
-              owner: context.repo.owner,
-              repo: context.repo.repo,
-              workflow_id
-            });
-
-            const previousRun = runs.data.workflow_runs.find(run => run.id !== context.runId);
-
-            if (!previousRun) {
-              core.info("No previous run found — skipping history copy.");
-              core.setOutput("run_id", "");
-            } else {
-              core.info(`Previous run ID: ${previousRun.id}`);
-              core.setOutput("run_id", previousRun.id);
-            }
-
-      - name: Download Allure History from Previous Run
-        if: success() || failure()
-        uses: actions/download-artifact@v4
-        with:
-          name: test-results
-          github-token: ${{ inputs.github-token }}
-          path: test-results-prev-run
-          run-id: ${{ steps.get-run-id.outputs.run_id }}
+        shell: bash
         continue-on-error: true
+        run: |
+          mkdir -p test-results/allure-results/history
+          for file in history.json categories-trend.json duration-trend.json retry-trend.json; do
+            curl -sfL "https://${GITHUB_REPOSITORY_OWNER}.github.io/${GITHUB_REPOSITORY##*/}/allure-report/history/$file" \
+              -o "test-results/allure-results/history/$file" || echo "$file not found"
+          done
 
       - name: Generate Allure Report
         if: success() || failure()
         shell: bash
         run: |
-          if [ -d test-results-prev-run/allure-report/history ]; then
-            cp -r test-results-prev-run/allure-report/history test-results/allure-results/history
-            echo "Allure history copied from previous run."
-          fi
-
           allure generate test-results/allure-results --clean -o test-results/allure-report
